### ISSUE TITLE
Where I can find the ESR and BVR in Odoo v 7?

### ISSUE THREAD

**Issue by diezcode** [jamotion/odoo-swiss-localization#1]
I have installed the l10n_ch modul, but i don't know where i can find the esr in the odoo system?

Can someone help me with this problem ?

Thanks

**Comment by renzo1974** [comment]
The ESR is not integrated in the l10n_ch module. You will need to install the l10n_ch_payment_slip module also...

**Comment by diezcode** [comment]
okay, thank you
